#!/usr/bin/env python3
"""
BCOS v2 Action - Post PR Comment

Posts a formatted comment to the pull request with the BCOS scan results.
"""

import json
import os
import base64
from urllib.request import Request, urlopen
from urllib.error import HTTPError


def main():
    """Post a PR comment with the BCOS scan results."""
    # Get inputs from environment
    github_token = os.environ.get("GITHUB_TOKEN", "")
    repo = os.environ.get("REPO", "")
    pr_number = os.environ.get("PR_NUMBER", "")
    report_json_b64 = os.environ.get("REPORT_JSON", "")
    
    if not github_token or not repo or not pr_number:
        print("Missing required environment variables. Skipping comment.")
        return
    
    if not report_json_b64:
        print("No report data available. Skipping comment.")
        return
    
    # Decode report
    try:
        report = json.loads(base64.b64decode(report_json_b64).decode('utf-8'))
    except Exception as e:
        print(f"Failed to decode report: {e}")
        return
    
    trust_score = report.get("trust_score", 0)
    tier_met = report.get("tier_met", False)
    cert_id = report.get("cert_id", "N/A")
    tier = report.get("tier", "L1")
    commit_sha = report.get("commit_sha", "unknown")
    timestamp = report.get("timestamp", "N/A")
    commitment = report.get("commitment", "N/A")
    schema = report.get("schema", "bcos-attestation/v2")
    score_breakdown = report.get("score_breakdown", {})
    
    # Determine badge color
    if trust_score >= 80:
        color = "brightgreen"
    elif trust_score >= 60:
        color = "green"
    elif trust_score >= 40:
        color = "yellowgreen"
    else:
        color = "red"
    
    # Generate badge URL
    badge_url = f"https://img.shields.io/badge/BCOS-{trust_score}/100-{color}"
    
    # Build comment
    tier_status = "✅" if tier_met else "❌"
    
    comment = f"""## 🛡️ BCOS v2 Scan Results

| Metric | Value |
|--------|-------|
| Trust Score | ![Trust Score]({badge_url}) |
| Tier | {tier} {tier_status} |
| Cert ID | `{cert_id}` |
| Commit | `{commit_sha[:8]}` |

<details>
<summary>Score Breakdown</summary>

| Component | Score |
|-----------|-------|
| License Compliance | {score_breakdown.get('license_compliance', 'N/A')} |
| Vulnerability Scan | {score_breakdown.get('vulnerability_scan', 'N/A')} |
| Static Analysis | {score_breakdown.get('static_analysis', 'N/A')} |
| SBOM Completeness | {score_breakdown.get('sbom_completeness', 'N/A')} |
| Dependency Freshness | {score_breakdown.get('dependency_freshness', 'N/A')} |
| Test Evidence | {score_breakdown.get('test_evidence', 'N/A')} |
| Review Attestation | {score_breakdown.get('review_attestation', 'N/A')} |

</details>

<details>
<summary>Attestation</summary>

- **Commitment**: `{commitment}`
- **Timestamp**: `{timestamp}`
- **Schema**: `{schema}`

</details>

---
*Generated by [BCOS v2 Action](https://github.com/Scottcjn/Rustchain/tree/main/.github/actions/bcos-action)*
"""
    
    # Post to GitHub API
    api_url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    
    req = Request(
        api_url,
        data=json.dumps({"body": comment}).encode('utf-8'),
        headers={
            'Authorization': f"token {github_token}",
            'Accept': 'application/vnd.github.v3+json'
        },
        method='POST'
    )
    
    try:
        response = urlopen(req)
        print(f"✅ Comment posted successfully: {response.status}")
    except HTTPError as e:
        error_body = e.read().decode() if e.fp else ""
        print(f"❌ Failed to post comment: {e.code} - {error_body}")


if __name__ == "__main__":
    main()
